import { defineNuxtPlugin, useRuntimeConfig } from '#app'
// @ts-expect-error — virtual template generated by the Nuxt module at build time
import { functionalOptions } from '#build/feature-toggles-functional-options.mjs'
import { createFeatureProvider, FEATURE_PROVIDER_KEY } from '../../src/core/FeatureProvider'
import Feature from '../../src/components/feature.vue'
import FeatureVariant from '../../src/components/feature-variant.vue'
import { vFeature } from '../../src/directives/vFeature'
import type { NuxtFeatureTogglesOptions } from '../module'
import type { FlagValue, FeatureTogglesOptions } from '../../src/core/types'

export default defineNuxtPlugin((nuxtApp) => {
  const config = useRuntimeConfig().public.featureToggles as NuxtFeatureTogglesOptions

  // On client: restore server-side flag snapshot from Nuxt payload to prevent hydration mismatch
  const ssrState = import.meta.client
    ? ((nuxtApp.payload as Record<string, unknown>).featureFlags as Record<string, FlagValue> | undefined)
    : undefined

  // `loader`/`rules` come from the module's generated template (see `configFile`
  // in nuxt.config.ts), since they're function-valued and never reach
  // runtimeConfig.public (which is JSON-serialized).
  const provider = createFeatureProvider({
    ...config,
    ...(functionalOptions as Partial<Pick<FeatureTogglesOptions, 'loader' | 'rules'>>),
    ssrState,
  })

  // On server: capture resolved flags after the page renders for payload embedding
  if (import.meta.server) {
    nuxtApp.hook('app:rendered', () => {
      ;(nuxtApp.payload as Record<string, unknown>).featureFlags = provider.serialize()
    })
  }

  nuxtApp.vueApp.provide(FEATURE_PROVIDER_KEY, provider)
  nuxtApp.vueApp.component('Feature', Feature)
  nuxtApp.vueApp.component('FeatureVariant', FeatureVariant)
  nuxtApp.vueApp.directive('feature', vFeature)

  return {
    provide: {
      // Access provider outside component setup: const { $featureToggles } = useNuxtApp()
      featureToggles: provider,
    },
  }
})
